spring.profiles: default

webConstant:
  runningMode: Dev
  resourceServer: http://127.0.0.1:8080/uimaster
  uploadServer: http://127.0.0.1:8080/uimaster/uploadFile
  websocketServer: http://127.0.0.1:8090
  resourcePath: ''
  isHTTPs: false
  isJAAS: false
  formatHTML: true
  customizedMode: false
  contextRoot: /uimaster
  ajaxServiceURL: /uimaster/ajaxservice
  cssRootPath: /css
  jsRootPath: /js
  webport: 8080
  hotdeployeable: true
  hiddenValueMask: '***'
  defaultOrgCode: jounioruser
  actionPath: /uimaster/webflow.do
  loginPath: /uimaster/login.do
  frameWrap: /uimaster
  loginPage: /uimaster/jsp/login.jsp
  iloginPage: /uimaster/jsp/ilogin.jsp
  indexPage: /uimaster/jsp/index.jsp
  mainPage: /uimaster/jsp/main.jsp
  errorPage: /uimaster/jsp/common/Failure.jsp
  timeoutPage: /uimaster/jsp/common/sessionTimeout.jsp
  nopermissionPage: /uimaster/jsp/common/noPermission.jsp
  ajaxHandlingError: true
  syncLoadJs: 
   - jquery.js
   - jquery-ui.js
   - jquery-mobile.js
   - uimaster.js
   - api.map.baidu.com/api
   - coupon-common.js
  commoncss:
   - ${webConstant.resourceServer}/uimaster/js/controls/swiper/swiper.css
   - /uimaster/css/jquery-dataTable.css
   - /uimaster/css/jquery-jstree.css
   - /uimaster/css/jquery-ui.css
   - /uimaster/css/iumaster.css
  commonMobcss:
   - /uimaster/js/controls/swiper/swiper.css
   - /uimaster/css/jquery-dataTable.css
   - /uimaster/css/jquery-jstree.css
   - /uimaster/css/jquery-ui.css
   - /uimaster/css/iumaster.css
  commonMobAppcss:
   - $APPROOT/js/controls/swiper/swiper.css #ssss
   - $APPROOT/css/jquery-dataTable.css
   - $APPROOT/css/jquery-jstree.css
   - $APPROOT/css/jquery-ui.css
   - $APPROOT/css/iumaster.css
  commonjs:
   - /uimaster/js/jquery.js
   - /uimaster/js/jquery-ui.js
   - /uimaster/js/controls/swiper/swiper.jquery.js
   - /uimaster/js/jquery-dataTable.js
   - /uimaster/js/jquery-jstree.js
   - /uimaster/js/uimaster.js
   - /uimaster/js/uimaster-widget.js
  commonMobjs:
   - /uimaster/js/jquery.js
   - /uimaster/js/jquery-ui.js
   - /uimaster/js/jquery-mobile.js
   - /uimaster/js/controls/swiper/swiper.jquery.js
   - /uimaster/js/jquery-jstree.js
   - /uimaster/js/uimaster.js
   - /uimaster/js/uimaster-widget.js
  commonMobAppjs:
   - $APPROOT/js/jquery.js
   - $APPROOT/js/jquery-ui.js
   - $APPROOT/js/jquery-mobile.js
   - $APPROOT/js/controls/swiper/swiper.jquery.js
   - $APPROOT/js/jquery-jstree.js
   - $APPROOT/js/uimaster.js
   - $APPROOT/js/uimaster-widget.js
  singleCommonCss: 
   org_shaolin_CustomerManagementTest: /uimaster/css/test1.css
  singleCommonAppCss: 
   org_shaolin_CustomerManagementTest_mob: /uimaster/css/test1.css
  singleCommonJs:
   org_shaolin_CustomerManagementTest: https://api.map.baidu.com/api?v=2.0&amp;ak=kT8czcw0fydHdXiGPGBOckX1
   org_shaolin_GlobalStatisticTest: 
    /uimaster/js/controls/map/raphael-min.js,
    /uimaster/js/controls/map/chinaMapConfig.js,
    /uimaster/js/controls/map/map.js
  singleCommonAppJs:
   org_shaolin_CustomerManagementTest_mob: https://api.map.baidu.com/api?v=2.0&amp;ak=kT8czcw0fydHdXiGPGBOckX1
   org_shaolin_GlobalStatisticTest_mob: 
     $APPROOT/js/controls/map/raphael-min.js,
     $APPROOT/js/controls/map/chinaMapConfig.js,
     $APPROOT/js/controls/map/map.js